# Generated by Django 3.1 on 2022-05-22 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名稱')),
                ('_type', models.CharField(max_length=50, verbose_name='型號')),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
                ('origin', models.CharField(max_length=50, verbose_name='產地')),
            ],
            options={
                'verbose_name': '產品',
                'verbose_name_plural': '產品',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_name', models.CharField(max_length=50, verbose_name='中文名稱')),
                ('english_name', models.CharField(max_length=50, verbose_name='英文名稱')),
            ],
            options={
                'verbose_name': '分類',
                'verbose_name_plural': '分類',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='影片連結')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
            ],
            options={
                'verbose_name': '影片',
                'verbose_name_plural': '影片',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tags'),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='圖片連結')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
            ],
            options={
                'verbose_name': '圖片',
                'verbose_name_plural': '圖片',
            },
        ),
    ]
