# Generated by Django 3.1 on 2022-05-22 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='產地'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.tags'),
        ),
    ]
