# Generated by Django 3.1 on 2022-06-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='url',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='型號'),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin',
            field=models.CharField(default='TW', max_length=50, verbose_name='產地'),
        ),
    ]
